# Google App Engine Standard - Go runtime
# Deploy: make gae-deploy
#
# Free tier safe: F1 instance, scales to zero when idle
# Static files served directly by GAE (faster, no instance hours)

runtime: go124

# Free tier settings
instance_class: F1
automatic_scaling:
  min_instances: 0
  max_instances: 1

env_variables:
  DIST_DIR: "./dist"

handlers:
  # Static directories served directly by GAE (no instance hours)
  - url: /images
    static_dir: dist/images

  - url: /static
    static_dir: dist/static

  # All other requests go to the Go app
  - url: /.*
    script: auto
